"""add user profile fields

Revision ID: b90d818dd45f
Revises: e0154ed6d8a0
Create Date: 2026-03-02 13:49:21.532196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b90d818dd45f'
down_revision: Union[str, None] = 'e0154ed6d8a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('base_cv_content', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('additional_info', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'additional_info')
    op.drop_column('users', 'base_cv_content')
    # ### end Alembic commands ###
